"""CLI: python -m failoverbench <wall | run | report | litellm-config>"""

from __future__ import annotations

import sys

USAGE = """failoverbench — a crash-test lab for LLM gateways and SDKs

  python -m failoverbench wall  [--port 8401] [--profile fast|full] [-v]
  python -m failoverbench run   --system systems/reference.yaml [--profile fast|full] [--only S01,S08]
  python -m failoverbench report [--profile fast|full]
  python -m failoverbench litellm-config [--wall-url http://host.docker.internal:8401/v1] > gateways/litellm/litellm.yaml
"""


def litellm_config(argv):
    import argparse

    import yaml

    ap = argparse.ArgumentParser(prog="failoverbench litellm-config",
                                 description="Write a LiteLLM proxy config that routes every scenario model to the wall with its fallback.")
    ap.add_argument("--catalogue", default="scenarios/catalogue.yaml")
    ap.add_argument("--wall-url", default="http://host.docker.internal:8401/v1",
                    help="how the *gateway container* reaches the wall")
    ap.add_argument("--num-retries", type=int, default=2)
    ap.add_argument("--timeout", type=float, default=30)
    args = ap.parse_args(argv)
    with open(args.catalogue, encoding="utf-8") as fh:
        cat = yaml.safe_load(fh)
    default_fb = cat.get("default_fallback", "fb-ok")
    models = {default_fb, "fb-ok-noprefill"}
    fallbacks = []
    ctx_fallbacks = []
    for sc in cat["scenarios"]:
        fb = sc.get("fallback_model", default_fb)
        models.add(sc["model"])
        models.add(fb)
        fallbacks.append({sc["model"]: [fb]})
        ctx_fallbacks.append({sc["model"]: [fb]})
    model_list = [{"model_name": m, "litellm_params": {"model": f"openai/{m}", "api_base": args.wall_url, "api_key": "failoverbench"}}
                  for m in sorted(models)]
    cfg = {
        "model_list": model_list,
        "router_settings": {
            "num_retries": args.num_retries,
            "timeout": args.timeout,
            "fallbacks": fallbacks,
            "context_window_fallbacks": ctx_fallbacks,
        },
        "litellm_settings": {"drop_params": True},
        "general_settings": {"master_key": "sk-failoverbench"},
    }
    sys.stdout.write("# generated by `python -m failoverbench litellm-config` — do not edit by hand\n")
    yaml.safe_dump(cfg, sys.stdout, sort_keys=False)


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv or argv[0] in ("-h", "--help"):
        print(USAGE)
        return
    cmd, rest = argv[0], argv[1:]
    if cmd == "wall":
        from .wall import main as m
        m(rest)
    elif cmd == "run":
        from .runner import main as m
        m(rest)
    elif cmd == "report":
        from .report import main as m
        m(rest)
    elif cmd == "litellm-config":
        litellm_config(rest)
    else:
        print(USAGE)
        raise SystemExit(f"unknown command {cmd!r}")


if __name__ == "__main__":
    main()
